# Generated by Django 5.0.1 on 2025-04-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISCOPE_Recreate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='web_needed/default.png', null=True, upload_to=''),
        ),
    ]
