# Generated by Django 5.2 on 2025-05-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISCOPE_Recreate', '0002_alter_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/default.png', null=True, upload_to=''),
        ),
    ]
